<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Rows per page_MuiBackdrop-root MuiBackd_7e7281</name>
   <tag></tag>
   <elementGuidId>75f7163c-c18f-4bb5-b050-b5339c53058e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.MuiBackdrop-root.MuiBackdrop-invisible.muiltr-esi9ax</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[3]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c789c8b4-9731-4634-98a7-6b68b19e6693</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>b3531c1c-e98f-410e-9655-a35cc6685256</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiBackdrop-root MuiBackdrop-invisible muiltr-esi9ax</value>
      <webElementGuid>3e3ce3cd-5be5-4351-9e08-edbee7190cf2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;MuiPopover-root dropdown-menus MuiModal-root muiltr-ki6667&quot;]/div[@class=&quot;MuiBackdrop-root MuiBackdrop-invisible muiltr-esi9ax&quot;]</value>
      <webElementGuid>34bdfb4d-b6f7-4078-8c66-bfd527b85744</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div</value>
      <webElementGuid>b417046c-4f0b-401d-9125-48e1f1bc2b40</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
