<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Inactive</name>
   <tag></tag>
   <elementGuidId>a2eadc00-3c1b-403e-96cb-7e951c2b98af</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.MuiChip-label.MuiChip-labelSmall.muiltr-tavflp</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div[2]/div[3]/div[2]/div[3]/div/table/tbody/tr/td[2]/div/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>0432f988-4de0-4596-aef0-75bcdc047441</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiChip-label MuiChip-labelSmall muiltr-tavflp</value>
      <webElementGuid>9156bf6e-4e64-494a-9dee-86540d97e0f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Inactive</value>
      <webElementGuid>993e4c80-b002-44bd-a713-2953424e5d31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;flex muiltr-1928xwl&quot;]/div[@class=&quot;page-wrapper muiltr-1u3gw72&quot;]/div[@class=&quot;muiltr-15n222f&quot;]/div[@class=&quot;muiltr-1t70f2z&quot;]/div[@class=&quot;MuiTableContainer-root muiltr-kge0eu&quot;]/table[@class=&quot;MuiTable-root muiltr-1owb465&quot;]/tbody[@class=&quot;MuiTableBody-root muiltr-1xnox0e&quot;]/tr[@class=&quot;MuiTableRow-root tr active muiltr-k4ij1y&quot;]/td[@class=&quot;MuiTableCell-root MuiTableCell-body MuiTableCell-sizeMedium muiltr-xyr7qj&quot;]/div[@class=&quot;MuiChip-root MuiChip-filled MuiChip-sizeSmall MuiChip-colorDefault MuiChip-filledDefault inactive status muiltr-3wvm4r&quot;]/span[@class=&quot;MuiChip-label MuiChip-labelSmall muiltr-tavflp&quot;]</value>
      <webElementGuid>f80ac110-e576-449d-b6da-3c84532cf064</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div[3]/div[2]/div[3]/div/table/tbody/tr/td[2]/div/span</value>
      <webElementGuid>5efa54b2-0649-4186-b26d-d225b911dd59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Actions'])[1]/following::span[3]</value>
      <webElementGuid>bb7f072f-c176-4152-8729-51b2e9ab4761</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Created At'])[1]/following::span[3]</value>
      <webElementGuid>011255d1-8686-4b41-ab3b-85603fc5a105</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='User'])[1]/preceding::span[1]</value>
      <webElementGuid>5f9477b0-dbd9-48dd-9c19-8dcb959ed288</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='automation@techwards.co'])[1]/preceding::span[2]</value>
      <webElementGuid>ce41a60e-1a0a-4283-86b3-24a30d3dc812</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Inactive']/parent::*</value>
      <webElementGuid>d49a948b-6bf0-44c6-b958-a895bd622692</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/div/span</value>
      <webElementGuid>9efe2069-7a9a-4a03-9460-19dac14d7ff4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Inactive' or . = 'Inactive')]</value>
      <webElementGuid>6c34fb8f-686e-4436-88d1-9b6f84cff67f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
