<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>cite_httpswww.wikipedia.com</name>
   <tag></tag>
   <elementGuidId>3e8fe42d-e895-4f52-b9b5-cdd7910e927c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>cite.apx8Vc.tjvcx.GvPZzd.cHaqb</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rso']/div/div/div/div/div/a/div/div/div/cite</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>cite</value>
      <webElementGuid>a6b7fc8d-0b9f-41d6-95d1-640e54ef36c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>apx8Vc tjvcx GvPZzd cHaqb</value>
      <webElementGuid>cd2ffc01-df0c-4fba-8e80-fde86f3a7dfc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>7815c039-c99d-44df-bf26-0a44e3aadff7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>https://www.wikipedia.com</value>
      <webElementGuid>8393ea31-4cf2-4d36-904e-eba98617ac8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rso&quot;)/div[@class=&quot;MjjYud&quot;]/div[@class=&quot;g Ww4FFb vt6azd tF2Cxc asEBEc&quot;]/div[@class=&quot;kvH3mc BToiNc UK95Uc&quot;]/div[@class=&quot;Z26q7c UK95Uc jGGQ5e&quot;]/div[@class=&quot;yuRUbf&quot;]/a[1]/div[@class=&quot;TbwUpd NJjxre iUh30 apx8Vc ojE3Fb&quot;]/div[1]/div[@class=&quot;byrV5b&quot;]/cite[@class=&quot;apx8Vc tjvcx GvPZzd cHaqb&quot;]</value>
      <webElementGuid>318a8184-c9a0-45e1-9e3f-febe86cf2a1f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rso']/div/div/div/div/div/a/div/div/div/cite</value>
      <webElementGuid>18d1cd6e-3b75-4afa-bb19-b29c81f60287</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='wikipedia.com'])[2]/following::cite[1]</value>
      <webElementGuid>46593a0a-6b84-406e-8eee-7a54c8d37b37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Wikipedia'])[1]/following::cite[1]</value>
      <webElementGuid>5e4d8ba7-58b8-4fcc-bb54-1ca678fa3aee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='wikipedia.com'])[3]/preceding::cite[1]</value>
      <webElementGuid>98667f41-ed0a-4c8c-852a-aae924339e2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='https://www.wikipedia.com'])[2]/preceding::cite[1]</value>
      <webElementGuid>1e340131-6d7f-4c08-97d8-07b0bba85a15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='https://www.wikipedia.com']/parent::*</value>
      <webElementGuid>5f879b2d-f845-49fc-b34d-ae03da2b6c7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//cite</value>
      <webElementGuid>dec685d2-cb81-4735-83a6-f35b3a2561e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//cite[(text() = 'https://www.wikipedia.com' or . = 'https://www.wikipedia.com')]</value>
      <webElementGuid>7a9c9323-fcc6-48b5-b98c-2254c255fe8f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
