<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>cite_httpswww.youtube.com</name>
   <tag></tag>
   <elementGuidId>8c83da7e-d36d-4bc2-9937-fa281274c5dd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>cite.apx8Vc.tjvcx.GvPZzd.cHaqb</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rso']/div/div/div/div/div/div/div/div/a/div/div/div/cite</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>cite</value>
      <webElementGuid>7701045d-e0f7-4a2d-b6b0-47832d4d292a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>apx8Vc tjvcx GvPZzd cHaqb</value>
      <webElementGuid>d8e8b3d5-bcce-4925-b64a-01b386744f7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>64a323b2-4ea1-4352-bd27-0534f0b2cdf4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>https://www.youtube.com</value>
      <webElementGuid>a3a6567c-3602-4cd7-95ed-a1ba45c89338</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rso&quot;)/div[@class=&quot;MjjYud&quot;]/div[@class=&quot;g&quot;]/div[@class=&quot;BYM4Nd&quot;]/div[@class=&quot;eKjLze&quot;]/div[@class=&quot;g&quot;]/div[1]/div[@class=&quot;tF2Cxc&quot;]/div[@class=&quot;yuRUbf&quot;]/a[1]/div[@class=&quot;TbwUpd NJjxre iUh30 apx8Vc ojE3Fb&quot;]/div[1]/div[@class=&quot;byrV5b&quot;]/cite[@class=&quot;apx8Vc tjvcx GvPZzd cHaqb&quot;]</value>
      <webElementGuid>6ce8af85-c6e6-4e9f-8c1f-f548db951de5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rso']/div/div/div/div/div/div/div/div/a/div/div/div/cite</value>
      <webElementGuid>0d118422-de77-4ef3-9988-c93d173e0d16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='YouTube'])[2]/following::cite[1]</value>
      <webElementGuid>b3ef96bb-119b-483d-8605-f123b04e14f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='YouTube'])[1]/following::cite[1]</value>
      <webElementGuid>1cd33294-c3e7-40db-bafb-345d8f31dda7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='YouTube'])[3]/preceding::cite[1]</value>
      <webElementGuid>33d40070-32e2-4342-819f-c66ac60090d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='https://www.youtube.com'])[2]/preceding::cite[1]</value>
      <webElementGuid>6d3bafc2-6e95-468d-8719-20d57feda647</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='https://www.youtube.com']/parent::*</value>
      <webElementGuid>e80dd028-0368-4d76-aec8-e6a124ec52c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//cite</value>
      <webElementGuid>fe6a7cd5-a68b-4098-9eef-fbfe91e4b63b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//cite[(text() = 'https://www.youtube.com' or . = 'https://www.youtube.com')]</value>
      <webElementGuid>d390706c-6a29-4f3e-b928-4fc255ccc282</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
