<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Audit Trail_MuiInputBase-input muiltr-mnn31</name>
   <tag></tag>
   <elementGuidId>6d57dc5c-e050-47e3-b571-2a681ca1619a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.MuiInputBase-input.muiltr-mnn31</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>30905345-281c-4d9a-a36b-5f7c28577a42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search</value>
      <webElementGuid>92a6f95d-8e12-4a72-9200-04ada9c23eea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>42be0660-e2b4-4415-9192-317eccd87a6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data</name>
      <type>Main</type>
      <value>admin-audit-trail-filter-search-bar</value>
      <webElementGuid>f2f8b555-0060-4b6d-9245-43d0a18b964d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiInputBase-input muiltr-mnn31</value>
      <webElementGuid>db7d2533-a44c-4b6e-a43f-3f65a47cad22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;flex muiltr-1928xwl&quot;]/div[@class=&quot;page-wrapper muiltr-1u3gw72&quot;]/div[@class=&quot;muiltr-15n222f&quot;]/div[@class=&quot;muiltr-3ret6m&quot;]/div[@class=&quot;table-header-row MuiBox-root muiltr-0&quot;]/div[@class=&quot;muiltr-1t62lt9&quot;]/div[@class=&quot;muiltr-0&quot;]/div[@class=&quot;muiltr-130sn3p&quot;]/div[@class=&quot;search-box MuiBox-root muiltr-0&quot;]/div[@class=&quot;MuiInputBase-root MuiInputBase-colorPrimary Mui-focused muiltr-2w136l&quot;]/input[@class=&quot;MuiInputBase-input muiltr-mnn31&quot;]</value>
      <webElementGuid>00f1b9e9-0f91-4aeb-8adc-038a989a99a1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='']</value>
      <webElementGuid>5bd6ee7a-ed5a-4a2c-9aad-7e015d9500b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div[3]/div[2]/div/div/div/div/div/div/div/input</value>
      <webElementGuid>967c023d-d1c0-4bde-bf52-c552dfb4079a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>efc53422-94d4-45de-b781-4c180947b58a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Search' and @type = 'text']</value>
      <webElementGuid>514d04c6-f61b-4760-a069-86f980183acc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
